name: ♻ CI
on: 
  workflow_call:
  pull_request:
    branches: 
      - main 

permissions:
  contents: read

jobs:
  lint:
    name: 🔎 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pylint src

  build:
    name: 🏗 Build
    runs-on: windows-latest
    needs: lint
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          cache: 'pip'
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller convert.spec
      - uses: actions/upload-artifact@v7
        with:
          path: dist/*

